name: Data Preprocessing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  preprocess:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy scikit-learn
    
    - name: Run preprocessing
      run: |
        cd preprocessing
        python automate_Yusuf-Arist.py
        cd ..
    
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update preprocessed data" && git push)
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
